name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      JWTSigningKey: ${{ secrets.JWTSigningKey }}
      UserAgent: ${{ secrets.UserAgent }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jjasloot/ovdb:$(date +%s) --build-arg JWTSigningKey --build-arg UserAgent
